- core-sdk-samples/higgs-shop-sample-app/package-lock.json
- core-sdk-samples/higgs-shop-sample-app/package.json
- core-sdk-samples/higgs-shop-sample-app/src/contexts/theme.tsx
- core-sdk-samples/higgs-shop-sample-app/yarn.lock
> feat: add Lato font to UI

- core-sdk-samples/higgs-shop-sample-app/src/components/MessageModal/MessageModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/MessageModal/index.tsx
- core-sdk-samples/higgs-shop-sample-app/src/constants/index.ts
- core-sdk-samples/higgs-shop-sample-app/src/layouts/App/index.tsx
Add Dialog if API Key is missing.
> feat: add Dialog to warn if API Key is missing

- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx
- core-sdk-samples/higgs-shop-sample-app/src/contexts/UserDetails.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/AccountDetails/AccountDetails.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/AccountDetails/LoginView.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/AccountDetails/index.tsx
- core-sdk-samples/higgs-shop-sample-app/src/layouts/App/index.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/layouts/App/index.tsx
- core-sdk-samples/higgs-shop-sample-app/src/pages/AccountPage/AccountPage.tsx
- core-sdk-samples/higgs-shop-sample-app/src/pages/AccountPage/index.tsx
Add Account Details Page with IDSync Workflow for Login and Logout.
> feat: add Identity workflow and Account Details page

- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenuItem.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/StartShoppingModal/StartShoppingModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/contexts/theme.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/AccountDetails/AccountDetails.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/AccountDetails/LoginView.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/OrderDetails/OrderDetailsCard.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/OrderDetails/OrderDetailsCustomerDetails.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/OrderDetails/OrderDetailsCustomerDetails.tsx
- core-sdk-samples/higgs-shop-sample-app/src/features/OrderDetails/OrderDetailsTotals.tsx
- core-sdk-samples/higgs-shop-sample-app/src/pages/ProductDetailPage/ProductDetailPage.tsx
Adjust padding and spacing around UI components and other design revisions/clean up
> fix: Design Revisions

- .github/PULL_REQUEST_TEMPLATE.md
- core-sdk-samples/higgs-shop-sample-app/.github/PULL_REQUEST_TEMPLATE.md
Move PR Request Template file to the proper location.
> ci: move PR Request Template file

- core-sdk-samples/higgs-shop-sample-app/CHANGELOG.md
- core-sdk-samples/higgs-shop-sample-app/package-lock.json
- core-sdk-samples/higgs-shop-sample-app/package.json
- core-sdk-samples/higgs-shop-sample-app/scripts/release.sh
Cutting initial release before we switch to automated semantic release
> chore: Manually Cut first Release

- core-sdk-samples/higgs-shop-sample-app/.eslintrc.json
Add prettier rule to allow all line endings
- {explain how this has been tested, and what additional testing should be done}
- Closes https://go.mparticle.com/work/REPLACEME
> fix: Add prettier rule to allow all line endings

- core-sdk-samples/higgs-shop-sample-app/public/index.html
> style: add more awesome

- .github/workflows/higgs-shop-sample-app-release.yml
> ci: revise release sync process

- core-sdk-samples/higgs-shop-sample-app/package-lock.json
- core-sdk-samples/higgs-shop-sample-app/package.json
- core-sdk-samples/higgs-shop-sample-app/yarn.lock
- Update version references of mParticle library and types to 2.15.x
- Fixes #71 and #72
> feat: update mParticle version and type def to 2.15.x

- core-sdk-samples/higgs-shop-sample-app/src/pages/AccountPage/AccountPage.tsx
- Update usage of Logout Method based on changes in DefinitelyTyped Library. Merge this in once this PR has been merged.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59832
- Closes https://go.mparticle.com/work/SQDSDKS-3552
> fix: Update Higgs Shop Logout Implementation

- .github/workflows/higgs-shop-sample-app-pull-request.yml
- Add Node v17.x to testing matrix
- Closes https://go.mparticle.com/work/SQDSDKS-3652
> Add 17.x to PR testing matrix

- .github/workflows/higgs-shop-sample-app-release.yml
- Remove Data Plan Fetch from Release Process
> ci: remove-data-plan-fetch-from-release

- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyHeaderBar/APIKeyHeaderBar.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyHeaderBar/APIKeyHeaderBar.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyHeaderBar/index.tsx
- core-sdk-samples/higgs-shop-sample-app/src/contexts/theme.tsx
- core-sdk-samples/higgs-shop-sample-app/src/layouts/App/index.tsx
- Create UI Header Element for Hosted Sample App Desktop View
- Manual Testing
- Closes https://go.mparticle.com/work/SQDSDKS-4099
> feat: Create UI Component for API Key Desktop Header

- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx
- Create UI Header Element for Hosted Sample App Desktop View
- Manual Testing
- Closes https://go.mparticle.com/work/SQDSDKS-4100
> feat: Create UI Component for API Key Mobile Dashboard

- core-sdk-samples/higgs-shop-sample-app/.prettierrc
- Update Prettier config to respect both Windows and Mac line endings
- Run automated tests and linting
- Closes https://go.mparticle.com/work/SQDSDKS-3680
> fix: Update Prettierrc to support Windows

- .github/workflows/test-gh-deploy.yml
- core-sdk-samples/higgs-shop-sample-app/package-lock.json
- core-sdk-samples/higgs-shop-sample-app/package.json
- core-sdk-samples/higgs-shop-sample-app/yarn.lock
- Set up a Github Action and Package Script to bundle and deploy the sample app to Github Pages as a hosted sample app
- Github Action should run after the `Higgs Shop Release` job completes successfully
- Depends on #138 to be merged first
- Manually test deployment by temporarily decoupling from the Higgs Shop release and changing the repo's default branch to this PR branch
- Closes https://go.mparticle.com/work/SQDSDKS-4101
> feat: Set up Higgs Shop for Github Pages Deployment

- .github/workflows/higgs-shop-deploy-github-pages.yml
- Revise Higgs Shop Deployment Github Action to run once Higgs Shop Release completes successfully
> ci: Revise Github Pages Deployment

- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyHeaderBar/APIKeyHeaderBar.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyHeaderBar/APIKeyHeaderBar.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEntryModal.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEntryModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEnvMessageModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyRemoveConfirmationModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyUpdateModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/ModalContainer/ModalContainer.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/ModalContainer/index.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/StartShoppingModal/StartShoppingModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/constants/index.ts
- Refactor Modals into a reusable component
- Adjust margins so that dialog container fills most of the mobile screen
- Refactor URLS into constants
- {explain how this has been tested, and what additional testing should be done}
- Closes https://go.mparticle.com/work/SQDSDKS-4263
> fix: Update margins for Mobile Modals

- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEntryModal.test.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEntryModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/APIKeyModal/APIKeyEnvMessageModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/MessageModal/MessageModal.tsx
- core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx
- core-sdk-samples/higgs-shop-sample-app/src/contexts/theme.tsx
- core-sdk-samples/higgs-shop-sample-app/src/models/Products.ts
- Revise Hosted Sample App based on design feedback. Please review attached ticket for specific details.
- Closes https://go.mparticle.com/work/SQDSDKS-4103
> fix: Design Fit and Finish

- .github/workflows/dependabot-automerge.yml
- .github/workflows/pull-request.yml
- Revise Pull Request process to improve security by removing pull_request_target
- Closes https://go.mparticle.com/work/SQDSDKS-4283
> ci: Remove pull_request_target references

- README.md
- core-sdk-samples/higgs-shop-sample-app/README.md
- Add Links to Hosted Sample App
- Closes https://go.mparticle.com/work/SQDSDKS-4411
> docs: Add Link to Hosted Sample Apps

- .github/workflows/dependabot-branch-rebase.yml
1. PR target branch should be against development
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-branch-check-name.yml
Set up job to inherit token
- {explain how this has been tested, and what additional testing should be done}
- Closes https://go.mparticle.com/work/ci/SQDSDKS-5213
> ci: add in missing inherit in rebase job

- .github/workflows/higgs-shop-deploy-github-pages.yml
- .github/workflows/higgs-shop-sample-app-pull-request.yml
- .github/workflows/higgs-shop-sample-app-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/sync-higgs-shop-data-plan.yml
1. PR target branch should be against development
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-branch-check-name.yml
- Remove jobs that reference Node 12
- {explain how this has been tested, and what additional testing should be done}
- Closes https://go.mparticle.com/work/SQDSDKS-5214
> ci: Remove actions that use Node 12

- .github/workflows/higgs-shop-sample-app-pull-request.yml
1. PR target branch should be against development
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/stable/.github/workflows/pr-branch-check-name.yml
Add node 18 to test matrix for Higgs Shop
NA
- Closes https://go.mparticle.com/work/ci/SQDSDKS-3711
> ci: Add node 18.x to build/tests
